"use client";

import Card from "@/components/Card";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CardType } from "@/types/CardType";


type Card = {
  title: string;
  body: string;
  author: string;
};

// This is our Home component.
// In Next.js, this is our main page (http://localhost:3000)
export default function Home() {
  const [cards, setCards] = useState<CardType[]>([]);
  const [error, setError] = useState<boolean>(false);
  const [failedToLoad, setFailedToLoad] = useState<boolean>(false);

  const handleLoad = async () => {
    try {
      const res = await fetch("/api/cards", {
        method: "GET",
      });
      console.log(res);
      if (res.status === 200) {
        const data = await res.json();
        setCards(data);
      }
    } catch (e) {
      setError(true);
    }
  };

  useEffect(() => {
    handleLoad();
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
        if (cards.length === 0) {
            setFailedToLoad(true);
        }
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-4 md:container mx-auto">
          {cards.length > 0 ? (
            <div> 
                <p className="text-2xl underline">Unstyled card Details:</p>
                <p>{cards[0].title}</p>
                <p>{cards[0].body}</p>
                <p>{cards[0].author}</p>
            </div>
          ) : failedToLoad ? (
            <p className="text-xl text-center">Card failed to load</p>
        ) : <p className="text-xl text-center">Loading card...</p>}
      </main>
    </>
  );
}
